package com.veritis.spring.hibernate;
// Generated Sep 4, 2012 7:30:07 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Emp generated by hbm2java
 */
public class Emp  implements java.io.Serializable {


     private Integer empno;
     private String name;
     private String desig;
     private double salary;
     private Set students = new HashSet(0);

    public Emp() {
    }

	
    public Emp(String name, String desig, double salary) {
        this.name = name;
        this.desig = desig;
        this.salary = salary;
    }
    public Emp(String name, String desig, double salary, Set students) {
       this.name = name;
       this.desig = desig;
       this.salary = salary;
       this.students = students;
    }
   
    public Integer getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDesig() {
        return this.desig;
    }
    
    public void setDesig(String desig) {
        this.desig = desig;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }

    public String toString(){
        return "Employee No "+empno+"\nEmployee Name "+name+"\nEmployee Desig "+desig+"\nEmployee Salary"+salary+"\n";
    }


}


