package com.veritis.spring.hibernate;
// Generated Sep 4, 2012 7:30:07 PM by Hibernate Tools 3.2.1.GA



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer stdid;
     private Emp emp;
     private String stdname;

    public Student() {
    }

    public Student(Emp emp, String stdname) {
       this.emp = emp;
       this.stdname = stdname;
    }
   
    public Integer getStdid() {
        return this.stdid;
    }
    
    public void setStdid(Integer stdid) {
        this.stdid = stdid;
    }
    public Emp getEmp() {
        return this.emp;
    }
    
    public void setEmp(Emp emp) {
        this.emp = emp;
    }
    public String getStdname() {
        return this.stdname;
    }
    
    public void setStdname(String stdname) {
        this.stdname = stdname;
    }




}


